name: BuildAndTest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setting up working directory
      run: make init
    - name: Compile files
      run: make asm proc
    - name: Compile tests
      run: |
        ./asm.exe examples/fibonacciNumber.vasm fib.bin
        ./asm.exe examples/quadraticEquation.vasm quadeq.bin
    - name: Run tests
      run: |
        ./proc.exe fib.bin
        ./proc.exe quadeq.bin
        
      
